# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x03lib\"\x1c\n\x0bMessageBool\x12\r\n\x05value\x18\x01 \x01(\x08\"%\n\nGeneralMsg\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"7\n\x08\x43\x46ileMsg\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfile_info\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xdb\x01\n\x06\x43lient\x12,\n\x04Ping\x12\x10.lib.MessageBool\x1a\x10.lib.MessageBool\"\x00\x12/\n\x07\x43ommand\x12\x0f.lib.GeneralMsg\x1a\x0f.lib.GeneralMsg\"\x00\x30\x01\x12\x39\n\x13\x44ownloadFileCommand\x12\x0f.lib.GeneralMsg\x1a\r.lib.CFileMsg\"\x00\x30\x01\x12\x37\n\x11UploadFileCommand\x12\r.lib.CFileMsg\x1a\x0f.lib.GeneralMsg\"\x00(\x01\x32\xd7\x01\n\x02\x41I\x12,\n\x04Ping\x12\x10.lib.MessageBool\x1a\x10.lib.MessageBool\"\x00\x12/\n\x07\x43ommand\x12\x0f.lib.GeneralMsg\x1a\x0f.lib.GeneralMsg\"\x00\x30\x01\x12\x39\n\x13\x44ownloadFileCommand\x12\x0f.lib.GeneralMsg\x1a\r.lib.CFileMsg\"\x00\x30\x01\x12\x37\n\x11UploadFileCommand\x12\r.lib.CFileMsg\x1a\x0f.lib.GeneralMsg\"\x00(\x01\x32\x35\n\x08NetShell\x12)\n\x03log\x12\x0f.lib.GeneralMsg\x1a\x0f.lib.GeneralMsg\"\x00\x32\x34\n\x04Test\x12,\n\x04Ping\x12\x10.lib.MessageBool\x1a\x10.lib.MessageBool\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEBOOL']._serialized_start=21
  _globals['_MESSAGEBOOL']._serialized_end=49
  _globals['_GENERALMSG']._serialized_start=51
  _globals['_GENERALMSG']._serialized_end=88
  _globals['_CFILEMSG']._serialized_start=90
  _globals['_CFILEMSG']._serialized_end=145
  _globals['_CLIENT']._serialized_start=148
  _globals['_CLIENT']._serialized_end=367
  _globals['_AI']._serialized_start=370
  _globals['_AI']._serialized_end=585
  _globals['_NETSHELL']._serialized_start=587
  _globals['_NETSHELL']._serialized_end=640
  _globals['_TEST']._serialized_start=642
  _globals['_TEST']._serialized_end=694
# @@protoc_insertion_point(module_scope)
